name: Sanity Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.1"
      - name: Run sanity tests
        run: |
          bash scripts/run_sanity_tests.sh
